#pragma once

/* NOTE: DO NOT DEFINE NEW CONSTANTS IN THIS FILE! THIS FILE IS A COPY! */

/*
 * VE_REG_BMS_ERROR - 0x2101
 * @note Bit 1-27 of VE_REG_LYNX_ION_BMS_ERROR_FLAGS maps to value 1-27 of VE_REG_BMS_ERROR.
 * un8 error
 */
#define VE_VDATA_BMS_ERROR_NONE 					0
#define VE_VDATA_BMS_ERROR_BATTERY_INIT				1
#define VE_VDATA_BMS_ERROR_NO_BATTERY_FOUND			2
#define VE_VDATA_BMS_ERROR_UNKNOWN_PRODUCT			3
#define VE_VDATA_BMS_ERROR_BAT_TYPE					4
#define VE_VDATA_BMS_ERROR_NR_OF_BAT				5
#define VE_VDATA_BMS_ERROR_NO_SHUNT_FND				6
#define VE_VDATA_BMS_ERROR_MEASURE					7
#define VE_VDATA_BMS_ERROR_CALCULATE				8
#define VE_VDATA_BMS_ERROR_BAT_NR_SER				9
#define VE_VDATA_BMS_ERROR_BAT_NR					10
#define VE_VDATA_BMS_ERROR_HARDWARE_FAILURE			11
#define VE_VDATA_BMS_ERROR_WATCHDOG					12
#define VE_VDATA_BMS_ERROR_OVER_VOLTAGE				13
#define VE_VDATA_BMS_ERROR_UNDER_VOLTAGE			14
#define VE_VDATA_BMS_ERROR_OVER_TEMPERATURE			15
#define VE_VDATA_BMS_ERROR_UNDER_TEMPERATURE		16
#define VE_VDATA_BMS_ERROR_IO_EXPANDER				17
#define VE_VDATA_BMS_ERROR_UNDER_CHARGE_STANDBY		18
#define VE_VDATA_BMS_ERROR_RESERVED_19				19
#define VE_VDATA_BMS_ERROR_CONTACTOR_STARTUP		20
#define VE_VDATA_BMS_ERROR_RESERVED_21				21
#define VE_VDATA_BMS_ERROR_ADC_FAILURE				22
#define VE_VDATA_BMS_ERROR_SLAVE_FAILURE			23
#define VE_VDATA_BMS_ERROR_RESERVED_24				24
#define VE_VDATA_BMS_ERROR_PRE_CHARGE				25
#define VE_VDATA_BMS_ERROR_CONTACTOR				26
#define VE_VDATA_BMS_ERROR_RESERVED_27				27
#define VE_VDATA_BMS_ERROR_SLAVE_UPDATE				28
#define VE_VDATA_BMS_ERROR_SLAVE_UPDATE_UNAVAILABLE	29
#define VE_VDATA_BMS_ERROR_CALIBRATION_DATA_LOST	30 // Non-volatile calibration data lost
#define VE_VDATA_BMS_ERROR_SETTINGS_DATA_INVALID	31 // Non-volatile settings data invalid/corrupted
#define VE_VDATA_BMS_ERROR_BMS_CABLE				32 // BMS cable error
#define VE_VDATA_BMS_ERROR_REF_VOLTAGE_FAILURE		33 // Reference voltage failure
#define VE_VDATA_BMS_ERROR_WRONG_SYSTEM_VOLTAGE		34
#define VE_VDATA_BMS_ERROR_PRE_CHARGE_TIMEOUT		35
#define VE_VDATA_BMS_ERROR_ATC_ATD_FAILURE			36

/* NOTE: DO NOT DEFINE NEW CONSTANTS IN THIS FILE! THIS FILE IS A COPY! */
