#ifndef DBUSSERVICENAME_H
#define DBUSSERVICENAME_H

#include <QObject>

class DBusServiceType : public QObject
{
	Q_OBJECT
	Q_ENUMS(ServiceType)

public:
	explicit DBusServiceType(QObject *parent = nullptr);

public:
	enum ServiceType {
		DBUS_SERVICE_UNKNOWN = -1,
		DBUS_SERVICE_MULTI,
		DBUS_SERVICE_BATTERY,
		DBUS_SERVICE_SOLAR_CHARGER,
		DBUS_SERVICE_PV_INVERTER,
		DBUS_SERVICE_AC_CHARGER,
		DBUS_SERVICE_TANK,
		DBUS_SERVICE_GRIDMETER,
		DBUS_SERVICE_GENSET,
		DBUS_SERVICE_MOTOR_DRIVE,
		DBUS_SERVICE_INVERTER,
		DBUS_SERVICE_SYSTEM_CALC,
		DBUS_SERVICE_TEMPERATURE_SENSOR,
		DBUS_SERVICE_GENERATOR_STARTSTOP,
		DBUS_SERVICE_DIGITAL_INPUT,
		DBUS_SERVICE_PULSE_COUNTER,
		DBUS_SERVICE_UNSUPPORTED,
		DBUS_SERVICE_METEO,
		DBUS_SERVICE_VECAN,
		DBUS_SERVICE_EVCHARGER,
		DBUS_SERVICE_HUB4,
		DBUS_SERVICE_ACLOAD,
		DBUS_SERVICE_FUELCELL,
		DBUS_SERVICE_DCSOURCE,
		DBUS_SERVICE_ALTERNATOR,
		DBUS_SERVICE_DCLOAD,
		DBUS_SERVICE_DCSYSTEM,
		DBUS_SERVICE_MULTI_RS,
		DBUS_SERVICE_PLATFORM
	} ;

	static DBusServiceType::ServiceType getServiceType(QString serviceName);


signals:

};

#endif // DBUSSERVICENAME_H
